-- MySQL Script generated by MySQL Workbench
-- mié 01 sep 2021 21:06:27 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProyectoMuebleria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ProyectoMuebleria` ;

-- -----------------------------------------------------
-- Schema ProyectoMuebleria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProyectoMuebleria` ;
USE `ProyectoMuebleria` ;

-- -----------------------------------------------------
-- Table `ProyectoMuebleria`.`Pieza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoMuebleria`.`Pieza` (
  `tipo` VARCHAR(40) NOT NULL,
  `cantidad_stock` INT NOT NULL,
  PRIMARY KEY (`tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoMuebleria`.`Asignacion_Precio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoMuebleria`.`Asignacion_Precio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `precio` DOUBLE NOT NULL,
  `utilizada` TINYINT NOT NULL,
  `tipo_pieza` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Asignacion_Precio_Pieza_idx` (`tipo_pieza` ASC) VISIBLE,
  CONSTRAINT `fk_Asignacion_Precio_Pieza`
    FOREIGN KEY (`tipo_pieza`)
    REFERENCES `ProyectoMuebleria`.`Pieza` (`tipo`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoMuebleria`.`Mueble`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoMuebleria`.`Mueble` (
  `nombre` VARCHAR(40) NOT NULL,
  `precio` DOUBLE NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoMuebleria`.`Ensamble_Pieza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoMuebleria`.`Ensamble_Pieza` (
  `nombre_mueble` VARCHAR(40) NOT NULL,
  `tipo_pieza` VARCHAR(40) NOT NULL,
  `cantidad_pieza` INT NOT NULL,
  PRIMARY KEY (`nombre_mueble`, `tipo_pieza`),
  INDEX `fk_Ensamble_Pieza_Mueble1_idx` (`nombre_mueble` ASC) VISIBLE,
  CONSTRAINT `fk_Ensamble_Pieza_Pieza1`
    FOREIGN KEY (`tipo_pieza`)
    REFERENCES `ProyectoMuebleria`.`Pieza` (`tipo`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Ensamble_Pieza_Mueble1`
    FOREIGN KEY (`nombre_mueble`)
    REFERENCES `ProyectoMuebleria`.`Mueble` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoMuebleria`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoMuebleria`.`Usuario` (
  `nombre` VARCHAR(50) NOT NULL,
  `tipo` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoMuebleria`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoMuebleria`.`Cliente` (
  `NIT` VARCHAR(15) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(60) NOT NULL,
  `municipio` VARCHAR(30) NULL,
  `departamento` VARCHAR(30) NULL,
  PRIMARY KEY (`NIT`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoMuebleria`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoMuebleria`.`Factura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_compra` DATE NOT NULL,
  `precio_compra` DOUBLE NOT NULL,
  `devolucion` TINYINT NULL,
  `NIT_cliente` VARCHAR(15) NOT NULL,
  `nombre_usuario` VARCHAR(50) NOT NULL,
  INDEX `fk_Factura_Cliente1_idx` (`NIT_cliente` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_Factura_Usuario1_idx` (`nombre_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Factura_Cliente1`
    FOREIGN KEY (`NIT_cliente`)
    REFERENCES `ProyectoMuebleria`.`Cliente` (`NIT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Usuario1`
    FOREIGN KEY (`nombre_usuario`)
    REFERENCES `ProyectoMuebleria`.`Usuario` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoMuebleria`.`Ensamble_Mueble`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoMuebleria`.`Ensamble_Mueble` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_ensamble` DATE NOT NULL,
  `precio_ensamble` DOUBLE NOT NULL,
  `nombre_usuario` VARCHAR(50) NOT NULL,
  `nombre_mueble` VARCHAR(40) NOT NULL,
  `id_factura` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Ensamble_Mueble_Usuario1_idx` (`nombre_usuario` ASC) VISIBLE,
  INDEX `fk_Ensamble_Mueble_Mueble1_idx` (`nombre_mueble` ASC) VISIBLE,
  INDEX `fk_Ensamble_Mueble_Factura1_idx` (`id_factura` ASC) VISIBLE,
  CONSTRAINT `fk_Ensamble_Mueble_Usuario1`
    FOREIGN KEY (`nombre_usuario`)
    REFERENCES `ProyectoMuebleria`.`Usuario` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Ensamble_Mueble_Mueble1`
    FOREIGN KEY (`nombre_mueble`)
    REFERENCES `ProyectoMuebleria`.`Mueble` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Ensamble_Mueble_Factura1`
    FOREIGN KEY (`id_factura`)
    REFERENCES `ProyectoMuebleria`.`Factura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
